using System;
using System.IO;
using System.Text;
using System.Xml;
using System.Xml.XPath;
using TUtils.Common;
using TUtils.Common.Extensions;
using TUtils.Common.CommandLine;
using TUtils.Common.CommandLine.Common;

namespace Resx2Js
{
	class Program
	{
		static void Main(string[] args)
		{
			string resourceFilePath;
			string namespaceJs;
			TranspilerEnum transpiler;
			if (!ParseArgs(args, out resourceFilePath, out namespaceJs, out transpiler))
				return;

			if (!File.Exists(resourceFilePath))
			{
				Console.WriteLine($"file path {resourceFilePath} doesn't exist !");
				return;
			}

			try
			{
				var dirPath = Path.GetDirectoryName(resourceFilePath);
				var resourceName = Path.GetFileNameWithoutExtension(resourceFilePath);

				var allRessourcePaths = TFilePath.FindFilesInFolder(dirPath, filePath =>
				{
					var fp = new TFilePath(filePath);
					return ( fp.FileExtension2?.ToLower() == "resx"
					         || fp.FileExtension1?.ToLower() == "resx")
						   && (fp.FileBaseName?.EqualsIgnoreCase(resourceName)??false);
				});

				XPathNodeIterator datas = null;

				foreach (var resourcePath in allRessourcePaths)
				{
					var xml = File.ReadAllText(resourcePath);
					var fp = new TFilePath(resourcePath);
					var langIsoCode = fp.FileExtension2.IsNullOrEmpty() ? "default" : fp.FileExtension1;
					var doc = new XmlDocument();
					doc.LoadXml(xml);
					var nav = doc.CreateNavigator();
					datas = nav.Select("//data");
					var text = string.Format(@"
(function() {{
	'use strict';
	global.{2} = global.{2} || {{ }};
	global.{2}.Strings = global.{2}.Strings || function () {{ }};
	////////////////////////////////////////////////////////////////////////////////
	// {2}.Strings
	var ${2}_Strings = function() {{
	}};
	global.{2}.Strings[""{1}""] = ${2}_Strings;
	(function() {{{0}
	}})();
}})();",
						GetTranslations(datas,namespaceJs),
						langIsoCode,
						namespaceJs);

					var outPath = new TFilePath(resourcePath);
					if (fp.FileExtension2.IsNullOrEmpty())
						outPath.FileExtension1 = "js";
					else
						outPath.FileExtension2 = "js";

					using (var file = File.CreateText(outPath.ToString()))
					{
						file.Write(text);
					}
				}

				var csharpFileText = string.Format(@"
/*******************************************************************************
 * automatically generated by Resx2Js.exe
 *******************************************************************************/
{4}

namespace {1}
{{
	public class {2}
	{{
		#region private

		[{3}(""typeof global.{1}.Strings[{{isoCode}}]!= \""undefined\"""")]
		private static bool ExistLanguage(string isoCode)
		{{
			return false;
		}}

		[{3}(""global.{1}.Strings[{{isoCode}}][{{key}}]"")]
		private static string GetStringInternal(string isoCode, string key)
		{{
			return null;
		}}

		private static string GetString(string key)
		{{
			if (ExistLanguage(CurrentLanguageIsoCode))
			{{
				var text = GetStringInternal(CurrentLanguageIsoCode, key);
				if (text != null)
					return text;
			}}

			var txt = GetStringInternal(""default"", key);
			return txt;
		}}

		#endregion

		#region public

		/// <summary>
		/// Sets the current language as ISO code
		/// e.g.: ""de"", ""en"", """"(default)
		/// </summary>
		public static string CurrentLanguageIsoCode {{ get; set; }}

		#region Keys

		{0}

		#endregion

		#endregion
	}}
}}",
					GetResourceKeyDefinitions(datas),
					namespaceJs,
					resourceName,
					transpiler==TranspilerEnum.Saltarelle ? "InlineCode": "Template",
					transpiler==TranspilerEnum.Saltarelle ? "using System.Runtime.CompilerServices;": "using Bridge;");


				var csharpOutFilePath = new TFilePath(dirPath.Combine(resourceName));
				csharpOutFilePath.FileExtension1 = "cs";
				using (var file = File.CreateText(csharpOutFilePath.ToString()))
				{
					file.Write(csharpFileText);
				}
			}
			catch (Exception e)
			{
				Console.WriteLine(e.DumpException());
			}
		}

		private static object GetResourceKeyDefinitions(XPathNodeIterator datas)
		{
			var text = new StringBuilder();
			text.AppendLine();
			foreach (XPathNavigator dataNode in datas)
			{
				var name = dataNode.GetAttribute("name", "");
				text.AppendLine($"		public static string {name} {{ get {{ return GetString(\"{name.ToLower()}\"); }} }}");
			}
			return text.ToString();
		}

		private static string GetTranslations(XPathNodeIterator datas, string namespaceJs)
		{
			var text = new StringBuilder();
			text.AppendLine();
			foreach (XPathNavigator dataNode in datas)
			{
				var name = dataNode.GetAttribute("name", "");
				var selectSingleNode = dataNode.SelectSingleNode("value");
				if (selectSingleNode != null)
				{
					var value = selectSingleNode.Value;
					text.AppendLine($"		${namespaceJs}_Strings.{name.ToLower()} = \"{value}\";");
				}
			}
			return text.ToString();
		}

		private static bool ParseArgs(string[] args, out string resourceFilePath, out string namespaceJs, out TranspilerEnum transpiler)
		{
			var resxFilePathArgDef = new CommandLineArgDefinition().Init(() => new CommandArgString(), "resxFilePath");
			var namespaceJsArgDef = new CommandLineArgDefinition().Init(() => new CommandArgString(), "namespaceJs");
			var transpilerNameArgDef = new CommandLineArgDefinition().Init(() => new CommandArgString(), "transpiler");

			CommandLineArgs commandLineArgs;
			CommandLineParseResult commandLineResult;
			if (!CommandLineArgs.TryCreate(
				args,
				out commandLineArgs,
				out commandLineResult,
				resxFilePathArgDef, 
				namespaceJsArgDef,
				transpilerNameArgDef))
			{
				Console.WriteLine(commandLineArgs.UsageHint);
				resourceFilePath = null;
				namespaceJs = null;
				transpiler = TranspilerEnum.Saltarelle;
				return false;
			}

			resourceFilePath = commandLineArgs[resxFilePathArgDef].Value as string;
			namespaceJs = commandLineArgs[namespaceJsArgDef].Value as string;
			var transpilerTxt = commandLineArgs[transpilerNameArgDef].Value as string;
			transpiler = transpilerTxt.AsEnum(TranspilerEnum.Saltarelle);

			return true;
		}
	}
}
